"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";

const tabs = ["Home","Calls","Leads","Agent","Business"];
export default function Page(){
 const supabase=useMemo(()=>createClient(),[]); const [session,setSession]=useState(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:sub}=supabase.auth.onAuthStateChange((_e,n)=>setSession(n)); return()=>sub.subscription.unsubscribe()},[supabase]);
 if(loading)return <main className="center">Loading AliwCall…</main>; if(!session)return <Auth supabase={supabase}/>; return <Dashboard supabase={supabase} userId={session.user.id}/>;
}
function Auth({supabase}){const[mode,setMode]=useState("signup"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""); async function submit(e){e.preventDefault();setBusy(true);setMessage("");const r=mode==="signup"?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(r.error)setMessage(r.error.message);else if(mode==="signup"&&!r.data.session)setMessage("Check your email to confirm your account.")}
 return <main className="center authWrap"><section className="authCard"><div className="brand">AliwCall</div><h1>AI receptionist for small businesses</h1><p>Answer calls, capture leads and manage your business from one place.</p><form onSubmit={submit}><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Password" type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?"Please wait…":mode==="signup"?"Create account":"Sign in"}</button></form>{message&&<div className="notice">{message}</div>}<button className="linkBtn" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"Already have an account? Sign in":"New to AliwCall? Create account"}</button></section></main>}
function Dashboard({supabase,userId}){const[tab,setTab]=useState("Home"),[business,setBusiness]=useState(null),[agent,setAgent]=useState(null),[calls,setCalls]=useState([]),[leads,setLeads]=useState([]),[usage,setUsage]=useState({used_minutes:0,included_minutes:20}),[loading,setLoading]=useState(true);
 async function refresh(){setLoading(true);const m=await supabase.from("business_members").select("business_id, businesses(*)").eq("user_id",userId).limit(1).maybeSingle();const b=m.data?.businesses||null;setBusiness(b);if(b){const[a,c,l,u]=await Promise.all([supabase.from("agents").select("*").eq("business_id",b.id).limit(1).maybeSingle(),supabase.from("calls").select("*").eq("business_id",b.id).order("created_at",{ascending:false}).limit(50),supabase.from("leads").select("*").eq("business_id",b.id).order("created_at",{ascending:false}).limit(50),supabase.from("usage_monthly").select("*").eq("business_id",b.id).order("month",{ascending:false}).limit(1).maybeSingle()]);setAgent(a.data||null);setCalls(c.data||[]);setLeads(l.data||[]);if(u.data)setUsage(u.data)}setLoading(false)}
 useEffect(()=>{refresh()},[]); if(loading)return <main className="center">Loading dashboard…</main>; if(!business)return <BusinessSetup supabase={supabase} userId={userId} onDone={refresh}/>;
 return <main className="appShell"><header><div><div className="brand">AliwCall</div><small>{business.name}</small></div><button className="ghost" onClick={()=>supabase.auth.signOut()}>Sign out</button></header><section className="content">{tab==="Home"&&<Home agent={agent} calls={calls} leads={leads} usage={usage}/>} {tab==="Calls"&&<Calls calls={calls}/>} {tab==="Leads"&&<Leads leads={leads}/>} {tab==="Agent"&&<Agent supabase={supabase} business={business} agent={agent} onDone={refresh}/>} {tab==="Business"&&<Business supabase={supabase} business={business} onDone={refresh}/>}</section><nav>{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</nav></main>}
function BusinessSetup({supabase,userId,onDone}){const[name,setName]=useState(""),[category,setCategory]=useState(""),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");async function create(e){e.preventDefault();setBusy(true);setError("");const{data,error}=await supabase.from("businesses").insert({name,category:category||null,phone:phone||null}).select("*").single();if(error){setError(error.message);setBusy(false);return}const member=await supabase.from("business_members").insert({business_id:data.id,user_id:userId,role:"owner"});if(member.error){setError(member.error.message);setBusy(false);return}await supabase.from("usage_monthly").insert({business_id:data.id,month:new Date().toISOString().slice(0,7)+"-01",used_minutes:0,included_minutes:20});setBusy(false);onDone()}
 return <main className="center authWrap"><section className="authCard"><div className="brand">AliwCall</div><h1>Set up your business</h1><form onSubmit={create}><input placeholder="Business name" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="Category (Salon, Clinic, Shop…)" value={category} onChange={e=>setCategory(e.target.value)}/><input placeholder="Business phone" value={phone} onChange={e=>setPhone(e.target.value)}/><button disabled={busy}>{busy?"Creating…":"Create business"}</button></form>{error&&<div className="notice">{error}</div>}</section></main>}
function Home({agent,calls,leads,usage}){const left=Math.max(Number(usage.included_minutes)-Number(usage.used_minutes),0);return <><h1>Dashboard</h1><div className="hero"><span>AI Receptionist</span><strong>{agent?.enabled?"● ON":"○ OFF"}</strong></div><div className="grid"><Card n={calls.length} label="Calls"/><Card n={leads.length} label="Leads"/><Card n={usage.used_minutes} label="Minutes used"/><Card n={left} label="Free minutes left"/></div><div className="panel"><h3>Free plan</h3><p>{usage.used_minutes} of {usage.included_minutes} AI minutes used this month.</p><div className="track"><div className="fill" style={{width:`${Math.min((Number(usage.used_minutes)/Number(usage.included_minutes))*100,100)}%`}}/></div></div></>}
function Card({n,label}){return <div className="metric"><b>{n}</b><span>{label}</span></div>} function Calls({calls}){return <><h1>Calls</h1>{calls.length?calls.map(c=><div className="panel" key={c.id}><h3>{c.direction?.toUpperCase()} · {Math.ceil((c.duration_seconds||0)/60)} min</h3><p>{c.caller_number||c.callee_number||"Unknown"}</p><small>{c.summary||c.status}</small></div>):<div className="panel">No calls yet.</div>}</>} function Leads({leads}){return <><h1>Leads</h1>{leads.length?leads.map(l=><div className="panel" key={l.id}><h3>{l.name||"New lead"}</h3><p>{l.phone||"No phone saved"}</p><small>{l.requirement||l.status}</small></div>):<div className="panel">No leads yet.</div>}</>}
function Agent({supabase,business,agent,onDone}){const[name,setName]=useState(agent?.name||`${business.name} Receptionist`),[greeting,setGreeting]=useState(agent?.greeting||`Hello, thank you for calling ${business.name}. How can I help you today?`),[prompt,setPrompt]=useState(agent?.system_prompt||`You are the helpful AI receptionist for ${business.name}. Be concise and polite. Never invent prices or policies. Collect the caller's name, phone number and requirement when appropriate. Escalate uncertain questions to a human.`),[language,setLanguage]=useState(agent?.language||"en-IN"),[enabled,setEnabled]=useState(agent?.enabled||false),[busy,setBusy]=useState(false);async function save(e){e.preventDefault();setBusy(true);const p={business_id:business.id,name,greeting,system_prompt:prompt,language,voice:agent?.voice||"default",enabled,provider:agent?.provider||"vapi"};const r=agent?await supabase.from("agents").update(p).eq("id",agent.id):await supabase.from("agents").insert(p);setBusy(false);if(!r.error)onDone();else alert(r.error.message)}return <><h1>AI Agent</h1><form className="formPanel" onSubmit={save}><input value={name} onChange={e=>setName(e.target.value)}/><textarea value={greeting} onChange={e=>setGreeting(e.target.value)} rows="3"/><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows="8"/><input value={language} onChange={e=>setLanguage(e.target.value)}/><label className="switchRow"><span>Agent enabled</span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><button disabled={busy}>{busy?"Saving…":"Save agent"}</button></form></>}
function Business({supabase,business,onDone}){const[form,setForm]=useState({name:business.name||"",category:business.category||"",phone:business.phone||"",transfer_number:business.transfer_number||"",address:business.address||"",working_hours:business.working_hours||""});const set=(k,v)=>setForm({...form,[k]:v});async function save(e){e.preventDefault();const{error}=await supabase.from("businesses").update(form).eq("id",business.id);if(error)alert(error.message);else onDone()}return <><h1>Business</h1><form className="formPanel" onSubmit={save}><input placeholder="Business name" value={form.name} onChange={e=>set("name",e.target.value)}/><input placeholder="Category" value={form.category} onChange={e=>set("category",e.target.value)}/><input placeholder="Public phone" value={form.phone} onChange={e=>set("phone",e.target.value)}/><input placeholder="Human transfer number" value={form.transfer_number} onChange={e=>set("transfer_number",e.target.value)}/><input placeholder="Address / service area" value={form.address} onChange={e=>set("address",e.target.value)}/><textarea placeholder="Working hours" rows="4" value={form.working_hours} onChange={e=>set("working_hours",e.target.value)}/><button>Save business</button></form></>}
